### 회원가입
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "user2@beantalk.com",
  "nickname": "user2",
  "password": "user2user2"
}

### 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user3@beantalk.com",
  "password": "user3user3"
}

### GET 내 정보
GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjhjOWIxZWRkMGFkM2U1ZGQ5ZDgzMzc5IiwiaWF0IjoxNzU5MDY3MTIyLCJleHAiOjE3NTkxNTM1MjJ9.9rH4qHZE8tKqtIJqdk6XDRPS6WbCYdWqwUjXJrY3nPE

### GET 유저
GET http://localhost:3000/users/68c9b1edd0ad3e5dd9d83379
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjhjOWIxZWRkMGFkM2U1ZGQ5ZDgzMzc5IiwiaWF0IjoxNzU4MDQ4Nzg5LCJleHAiOjE3NTgxMzUxODl9.cTPtVwdwocG0tJNyWvZeRLG5UdT6tXXT-uO5e-BAWBE

### PATCH 유저
PATCH http://localhost:3001/users/edit
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjhjMDIxODY1MzNiZWQwMjZmODU1YWU4IiwiaWF0IjoxNzU3Njk0OTU1LCJleHAiOjE3NTc3ODEzNTV9.8ngCvURxTSQ9kxj9usiT1nlsHLJilIFkfgC5nR3gEiQ

{
  "nickname": "운영자1"
}

### DELETE 유저
DELETE http://localhost:3000/user/delete
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjhiZmYxY2NlYzUzYzcxYmJiOGQ2MDRhIiwiaWF0IjoxNzU3NDExOTkwLCJleHAiOjE3NTc0OTgzOTB9.SoUkVMHV3HI3-S6feG8mlQrRYeXynDvbBq9pGjVeDjI

### GET 알림
GET http://localhost:3000/users/me/notifications
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjhjMDIxODY1MzNiZWQwMjZmODU1YWU4IiwiaWF0IjoxNzU3OTg5OTA5LCJleHAiOjE3NTgwNzYzMDl9.RwYXJs3n799hhymXhHa_j72UOgdtwqLbfv5T_e703qE

### PATCH 알림

### DELETE 알림

### GET 내 게시글 목록
GET http://localhost:3000/me/my-posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhMjBlOTliNTRkNDk5ODg5YTE0IiwiaWF0IjoxNzcwNTM0NzQ0LCJleHAiOjE3NzA2MjExNDR9.UFP4r3kUg3i_VMTue7pNTqXkPuittkhIo-2W0NyrAOs

### GET 게시글 목록
GET http://localhost:3000/categories/promotion/posts
Content-Type: application/json

### GET 게시글
GET http://localhost:3000/categories/promotion/posts/6990cd385ed2affedea7aad3
Content-Type: application/json

### CREATE 게시글
POST http://localhost:3000/categories/promotion/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhMjBlOTliNTRkNDk5ODg5YTE0IiwiaWF0IjoxNzcxNjcwNDU0LCJleHAiOjE3NzE3NTY4NTR9.EJCNv9Q3ttue2IWcr1TkpvTTOsY2xu0Opm6v_vI55Jg

{
  "subCategory": "cafe",
  "title": "프로모션 게시글 작성 1",
  "content": "프로모션 게시글 작성 1"
}

### CREATE 게시글 (JOB)
POST http://localhost:3000/categories/job/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhMjBlOTliNTRkNDk5ODg5YTE0IiwiaWF0IjoxNzY5MzMxMDY5LCJleHAiOjE3Njk0MTc0Njl9.v4Jn_iCQGxQc27jIhCPhpurmZyfKmmpw2IbuX5Pz3Mk

{
  "subCategory": "seeking",
  "title": "job 게시글 테스트(seeking) 2",
  "content": "job 게시글 테스트(seeking) 2",
  "employmentType": "partTime",
  "position": "barista",
  "payAmount": 12000,
  "startTime": "12:00",
  "endTime": "18: 00"
}

### PATCH 게시글
PATCH http://localhost:3000/categories/promotion/posts/6990cd385ed2affedea7aad3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhMjBlOTliNTRkNDk5ODg5YTE0IiwiaWF0IjoxNzcxMDk3MDc1LCJleHAiOjE3NzExODM0NzV9.ENhfoWnv1lv8eXHNKuMXV3_1ZMHTflBPr2fQJL3D-4Q

{
  "title": "게시글 테스트 1 (수정)",
  "content": "게시글 테스트 1 (수정)"
}

### DELETE 게시글
DELETE http://localhost:3000/categories/promotion/posts/69883779072481095aa73189
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhMjBlOTliNTRkNDk5ODg5YTE0IiwiaWF0IjoxNzcwNTM0NzQ0LCJleHAiOjE3NzA2MjExNDR9.UFP4r3kUg3i_VMTue7pNTqXkPuittkhIo-2W0NyrAOs

### GET 댓글 목록
GET http://localhost:3000/categories/thread/posts/6931ff6f8c64ac8489acc69a/comments
Content-Type: application/json

### CREATE 댓글
POST http://localhost:3000/categories/promotion/posts/69998be5ef7efe522b7e3cf1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjk5OThhNWQ2MzE4MzVkMWM3MWI5YWMyIiwiaWF0IjoxNzcxODM4NDQ3LCJleHAiOjE3NzE5MjQ4NDd9.MyjwN-zx0A2uVtJJFzztwUQdHM6-sqMNWhSgLcgah_I

{
  "content": "댓글 테스트 user2"
}

### PATCH 댓글
PATCH http://localhost:3000/bbs/categories/news/posts/6915e564522049208a62d939/comments/691643d56c6601ff4661265e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhNGVlOTliNTRkNDk5ODg5YTFhIiwiaWF0IjoxNzYzMTQxNDE1LCJleHAiOjE3NjMyMjc4MTV9.8KlyXx2M-d3zafc_BXfaJEHQMhdpbxPBzMovmJy6xZg

{
  "content": "댓글 테스트 3 (수정 2)"
}

### DELETE 댓글
DELETE http://localhost:3000/bbs/categories/news/posts/69998be5ef7efe522b7e3cf1/comments/6914ea4ee99b54d499889a1a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhNGVlOTliNTRkNDk5ODg5YTFhIiwiaWF0IjoxNzYzMTQxNDE1LCJleHAiOjE3NjMyMjc4MTV9.8KlyXx2M-d3zafc_BXfaJEHQMhdpbxPBzMovmJy6xZg

### CREATE 답글
POST http://localhost:3000/categories/promotion/posts/69998be5ef7efe522b7e3cf1/comments/699c1be4ce67c9dd87f1a743/replies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjk5OThhNWQ2MzE4MzVkMWM3MWI5YWMyIiwiaWF0IjoxNzcxODM4NDQ3LCJleHAiOjE3NzE5MjQ4NDd9.MyjwN-zx0A2uVtJJFzztwUQdHM6-sqMNWhSgLcgah_I

{
  "content": "답글 테스트 user2"
}

### PATCH 답글
PATCH http://localhost:3000/bbs/categories/news/posts/6915e564522049208a62d939/comments/691af6cb0d5b27433afbf8ca/replies/691afc69bcac61f2b35f5a0d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhNGVlOTliNTRkNDk5ODg5YTFhIiwiaWF0IjoxNzYzMzc2MjAzLCJleHAiOjE3NjM0NjI2MDN9.XUXF1DvcpaJAB0kOLHQ3pMNaH8LKLkbp6h2EXvCYnrQ

{
  "content": "답글 테스트 1 (수정 1)"
}


### CREATE 좋아요
POST http://localhost:3000/bbs/categories/news/posts/6915e564522049208a62d939/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhNGVlOTliNTRkNDk5ODg5YTFhIiwiaWF0IjoxNzYzMzA4MjEyLCJleHAiOjE3NjMzOTQ2MTJ9.06rbad4yjdcWSKDimvsD6CD9j9qpbIE_dJ0489rJEPs

### DELETE 좋아요
DELETE http://localhost:3000/bbs/categories/news/posts/6915e564522049208a62d939/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhNGVlOTliNTRkNDk5ODg5YTFhIiwiaWF0IjoxNzYzMzA4MjEyLCJleHAiOjE3NjMzOTQ2MTJ9.06rbad4yjdcWSKDimvsD6CD9j9qpbIE_dJ0489rJEPs

### PATCH 토글 스크랩
PATCH http://localhost:3000/categories/promotion/posts/69998be5ef7efe522b7e3cf1/scraps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjk5OThhNWQ2MzE4MzVkMWM3MWI5YWMyIiwiaWF0IjoxNzcxODM4NDQ3LCJleHAiOjE3NzE5MjQ4NDd9.MyjwN-zx0A2uVtJJFzztwUQdHM6-sqMNWhSgLcgah_I

### GET 내 스크랩
GET http://localhost:3000/me/scraps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhMjBlOTliNTRkNDk5ODg5YTE0IiwiaWF0IjoxNzcwODMzMzk3LCJleHAiOjE3NzA5MTk3OTd9.ECt-moiNuc-WUF-ERxChSNARGeCHecRqYArcdq5DYMo

### GET 알림목록
GET http://localhost:3000/me/notifications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjkxNGVhMjBlOTliNTRkNDk5ODg5YTE0IiwiaWF0IjoxNzcwMjM1MjAyLCJleHAiOjE3NzAzMjE2MDJ9.O5dNkHSSHgdw5KLjen_bD1zW2NS9dojUAb3swUES5e4